version: '3.1'

services:
  app:
    container_name: tcc-pos-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    environment:
      MONGO_DATABASE: development-db
      MONGO_USER: backend-service
      MONGO_PASSWORD: password
    command: "npm run watch"
    networks:
      - tcc-pos-net

  mongodb:
    container_name: mongodb
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - ./database/data:/data/db
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: root-db
    networks:
      - tcc-pos-net

networks:
  tcc-pos-net:
    external: true
